services:
  app:
    build:
      context: .
    container_name: regional-products-app
    ports:
      - "8080:8080"
    volumes:
      - regional-products-app-data:/app/data
    environment:
      - SPRING_PROFILES_ACTIVE=prod

volumes:
  regional-products-app-data:
